services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: coworkly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coworkly_gjj
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - coworkly-network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=coworkly_gjj
      - DB_NAME=coworkly
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
    networks:
      - coworkly-network

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   networks:
  #     - coworkly-network

volumes:
  postgres-data:

networks:
  coworkly-network: